### ISSUE TITLE
Sources contract

### ISSUE THREAD

**Issue by dwf** [bartvm/fuel#62]
Is it assumed that sources are fully "parallel", i.e. same number of examples in each?

Two issues come to mind:

* Some datasets, including recent ImageNet challenge datasets, do not have test set groundtruth. It would be nice to include test data images even if there are no labels. One could define an "unknown" label but this might get messy.
* Some datasets include rather extensive metadata (I'm thinking of tree-structured prediction tasks, needing to put the encoded tree somewhere). Is this a "source"? Presumably not, but maybe?

**Comment by bartvm** [comment]
I guess there's something to say for letting sources be of unequal length. Otherwise source naming becomes awkward. Source names are deduced from their names in the HDF5 file, so if you need to store the test data in a separate HDF5 group, the source name would suddenly change. That can be really inconvenient. All the arguments used when first suggested to not split up the data still apply as well I guess.

It requires some error checking in the `H5PYDataset` though, which should raise an error when a user tries to load a combination of sets and sources that doesn't work. This should be relatively straightforward though: If no set is given, assert that all sources are of equal length. If a set is specified, assert that the highest index belonging to this set is less than the size of the smallest source requested.

We could make one assumption to simplify the code: Labelled examples need to come first, and different sources are aligned otherwise. This makes it impossible to have multiple labels though if their alignments differ. For example, if we have 3 sources `A`, `B` and `C` of lengths 10, 7 and 7, where `A[0:7]` have labels `B[0:7]`, and examples `A[3:10]` have supplementary labels `C[0:7]`...

If we want to support this case, we'd have to normalize everything to refer to an index based on the longest array. So we would have `B` and `B_indices = range(0, 7)` and `C_indices = range(3, 10)` (but for more complicated examples these could even be non-contiguous).

**Comment by vdumoulin** [comment]
I had a chat with @dwf offline and I think we found a good solution, at least for his first point.

I propose that we replace setting arbitrary split names in `File.attrs` and instead use a single attribute, named `'split'`, which is a numpy array organized as follows:

* Axis 0 represents splits, and its size is the number of available splits
* Axis 1 represents data sources, and its size is the total number of available data sources
* Axis 2 has size 6 and is organized as follows:
    * First element is the split name
    * Second element is the data source name
    * Third element is the start index
    * Fourth element is the stop index
    * Fifth element is a boolean indicating whether or not the data source is available for this split
    * Sixth element is a comment string (that can be leaved blank)

This lets us easily and unambiguously define splits containing a variable number of data sources.

**Comment by dwf** [comment]
Just to be clear, we're talking about a 1-d NumPy structured array, e.g.
pandas DataFrame "lite", using a compound dtype of (str, str, int64, int64,
bool, str). The strings need defined maximum lengths, which we can either
adopt one standard or choose the maximum length necessary at construction
time.

**Comment by bartvm** [comment]
Sounds good, but does this introduce the limitation that splits need to be contiguous, right? Although I guess we can always find a hacky workaround if the need arises (e.g. start index equal to `-1` means that the comment string contains the name of the HDF5 dataset with the indices).

**Comment by vdumoulin** [comment]
I'd rather use dataset attributes to store split indices if possible, but that sounds like a reasonable solution.

There's also the matter of concatenating dataset splits (_e.g._ using `'train' + 'valid'`) which should eventually be tackled, but for the moment I think it is sufficient to implement the basic case of contiguous splits and create tickets for these more exotic cases.

**Comment by bartvm** [comment]
I agree that we don't need to cover these exotic cases straight away, as long as we don't implement something that excludes us from ever addressing them. I don't think that's the case here, so I think it's a nice way to go.

**Comment by vdumoulin** [comment]
@bartvm @dwf I started a PR (#64) so we can discuss this in more concrete terms.

**Comment by vdumoulin** [comment]
Are there things in this issue that haven't been covered by #64 ?

**Comment by dwf** [comment]
I think this is pretty much adequately addressed by #64, so I'm closing.
